In [16]:
import numpy as np

#creating numpy array
arr = np.array([3,5,7,9,11,15,18,22])

#converting 1D array to 2D array
arr2 = arr[1:6]

#slice starting from 3rd value to end
arr2 = arr[3:]

#slice 0 to 4 index
arr2 = arr[:5]

#using negative slicing
arr2 = arr[-4:-2]

#use step values using start and end values is empty
arr2 = arr[::3]

#use slicing with interval
arr2 = arr[3::4]

#use slicing a 2d arrays
arr = np.array([[3,5,7,9,11],[2,4,6,8,10]])
arr2 = arr[1:,1:3]

#slicing 3-D arrays
arr = np.array([[[3,5,7,9,11],[2,4,6,8,10]],[[5,7,8,9,2],[7,2,3,6,7]]])
arr2 = arr[0,1,0:2]

#finding  the datatype
arr1 = np.array([1,2,3])
arr2 = np.array([1.8,2.5,3.14])
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1,arr2,arr3.dtype)

#rever of data
arr =np.array([1,2,4,6,5,9,78,34,66,1,3,8,9,0])
print(arr[-7:-3])

#use concatenate() to join two arrays
arr = np.array([4,7,12])
arr1 = np.array([5,9,15])
arr = np.concatenate((arr,arr1))
print(arr)

#use concatenate() with axis
arr = np.array([[3,5],[7,9]])
arr1 = np.array([[11,15],[18,22]])
arr = np.concatenate((arr,arr1),axis=1)
print(arr)

#use np.stack () function to join array
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.stack((arr1,arr2),axis=1)
print(arr)

#use stacking along rows,columns and height
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.hstack((arr1,arr2))
arr4 = np.vstack((arr1,arr2))
arr5 = np.dstack((arr1,arr2))
print(arr3,arr4,arr5)

#use joining the two array along axis=none
arr = np.array([[3,5],[7,9]])
arr1 = np.array([[11,15],[18,22]])
arr = np.concatenate((arr,arr1),axis=None)
print(arr)





[1 2 3] [1.8  2.5  3.14] int32
[34 66  1  3]
[ 4  7 12  5  9 15]
[[ 3  5 11 15]
 [ 7  9 18 22]]
[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6] [[1 2 3]
 [4 5 6]] [[[1 4]
  [2 5]
  [3 6]]]
[ 3  5  7  9 11 15 18 22]
